name: Bash Tuts
baseurl: /bash
encoding: utf-8
exclude: ['Gemfile', 'Gemfile.lock']
kramdown:
  input: GFM

nav: [
  ['Overview',                    'index'             ],
  ['Working on CLI',              'working-on-cli'    ],
  ['Analyzing text files',        'analyze-text-files'],
  ['Command line pipes',          'command-line-pipes'],
  ['Basic File Management',       'file-management'   ],
  ['Process Management',          'process-management'],
  ['Regular Expressions',         'regex'             ],
]
